database:
  build: database
  volumes:
    - ./database/data:/var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: takayuki
      MYSQL_DATABASE: lifeapp
      MYSQL_USER: albio
      MYSQL_PASSWORD: albio
  container_name: lifeapp_node_db

node:
  build: node
  command: /opt/server/node_modules/forever/bin/forever /opt/server/app.js
  links:
    - database
  tty:
    true
  ports:
    - "3000:3000"
  volumes:
    - ./node:/opt/server/
  #environment:
    #DEBUG: "express:*"
  container_name: lifeapp_node
